---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
data:
  EMQX_MQTT__MAX_PACKET_SIZE: "{{ .Values.mqtt.maxPacketSize }}"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: toe
  namespace: {{ .Release.Namespace }}
data:
  CLIENT_ID: "{{ .Values.toe.deviceID }}"
  TOE_PROJECT: "{{ .Values.toe.gcpProject }}"
  TOE_IOT_REGISTRY: "{{ .Values.toe.teamSpace }}"
  TOE_DEVICE: "{{ .Values.toe.deviceID }}"
  OFFLINE_MODE: "{{ .Values.toe.offlineMode }}"
  DEBUG: "{{ .Values.toe.debug }}"
  EDGE_MQTT_MAX_PAYLOAD_SIZE: "{{ .Values.toe.edgeMqttMaxPayloadSize }}"
  EDGE_MQTT_QUEUE_LIMIT: "{{ .Values.toe.edgeMqttQueueLimit }}"
  EDGE_MQTT_CLEAN_SESSION: "{{ .Values.toe.edgeMqttCleanSession }}"
  CLOUD_MQTT_MAX_PAYLOAD_SIZE: "{{ .Values.toe.cloudMqttMaxPayloadSize }}"
  CLOUD_MQTT_QUEUE_LIMIT: "{{ .Values.toe.cloudMqttQueueLimit }}"
  CLOUD_MQTT_CLEAN_SESSION: "{{ .Values.toe.cloudMqttCleanSession }}"
  PUBLISH_K8S_EVENTS: "{{ .Values.toe.publishK8sEvents }}"
  USE_PUBLISH_QUEUES: "{{ .Values.toe.usePublishQueues }}"
