---
apiVersion: v1
kind: Secret
metadata:
  name: artifact-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.toe.pullSecret }}

---
apiVersion: v1
kind: Secret
metadata:
  name: artifact-registry-secret
  namespace: {{ .Values.toe.defaultNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.toe.pullSecret }}
