---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - nodePort: 31883
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: mqtt

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: mqtt
  ports:
    - nodePort: 31083
      port: 18083
      protocol: TCP
      targetPort: 18083

---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: toe-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
