---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teknoir
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: artifact-registry-secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teknoir
  namespace: {{ .Values.toe.defaultNamespace }}
imagePullSecrets:
  - name: artifact-registry-secret

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teknoir-controller-manager
  namespace: {{ .Release.Namespace }}
imagePullSecrets:
  - name: artifact-registry-secret
