# Values needed for the TOE
toe:
  # The deviceID is the unique identifier for the device within a TeamSpace
  deviceID: ""
  # The teamSpace is the unique identifier for the TeamSpace the device is part of
  teamSpace: ""
  # The domain is the base domain name for the cloud instance of the Teknoir platform
  domain: ""
  # The pullSecret is the TeamSpace private secret used to pull the container images
  pullSecret: ""
  # The gcpProject is the GCP project the device is part of, but for production this is always "teknoir"
  gcpProject: "teknoir"
  # The configHostDir is the directory where the configuration files are stored
  configHostPath: "/etc/teknoir"
  # The default namespace to use for Teknoir Plaform resources
  defaultNamespace: "default"
  # The resources for the TOE deployment
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 64Mi

  # TOE Default Configuration options
  offlineMode: "false"
  debug: "false"
  edgeMqttMaxPayloadSize: "1000000"
  edgeMqttQueueLimit: "1000"
  edgeMqttCleanSession: "true"
  cloudMqttMaxPayloadSize: "1000000"
  cloudMqttQueueLimit: "1000"
  cloudMqttCleanSession: "true"
  publishK8sEvents: "true"
  usePublishQueues: "true"

# Defaults for the EMQX Broker
mqtt:
  # The maximum packet size for MQTT messages
  maxPacketSize: 1MB

  #The resources for the MQTT deployment
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
