---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teknoir-manager-role
rules:
  - apiGroups:
      - teknoir.org
    resources:
      - toes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - teknoir.org
    resources:
      - toes/finalizers
    verbs:
      - update
  - apiGroups:
      - teknoir.org
    resources:
      - toes/status
    verbs:
      - get
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teknoir-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teknoir-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
